"""empty message

Revision ID: 6427ee72a89e
Revises: b49f05353862
Create Date: 2023-10-08 01:27:08.677312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6427ee72a89e'
down_revision = 'b49f05353862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothing_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_seller_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['brand_seller_id'], ['brand_seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clothing_item')
    # ### end Alembic commands ###
